name: Alex Wolf
favicon: null
layout_spectrum: 0.20987684628926218
typography_spectrum: 0.18298572790808976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7141589063685387
  lightness: 0.8437907842453569
  saturation: 0.6005119616165757
  rhythmicContrast: 0.34798554657027125
purpose: []
